### ISSUE TITLE
tests not running properly?

### ISSUE THREAD

**Issue by moimikey** [awesomeeng/zephjs#11]
hola,

forked the repo because i was wanting to make a PR to extend `css()` to accept a post-processor function (like post-css) but some problems arose:

1. missing deps
2. deps are outdated
3. mocha keeps timing  out

https://github.com/awesomeeng/zephjs/compare/master...moimikey:add-post-processor-support?expand=1

(also noticed you use explicit versions vs prefixed. not a biggie)

this is where i got... i can't exactly get the tests to run still. aside from that, thoughts on an additional option for a css post processor?

**Comment by arei** [comment]
I will black box this soon. I'm in the middle of a computer transition so it might be a few days.  That said...

I like the idea, but I would name it `transform` instead of `processFn` to be more consistent with similar systems in ZephJS.  

I'm not super familiar with post-css,  so I'm not sure how that works like this... I see that there is a `parser` function, but that returns a CSS AST, so I'm not sure how that plays in.  Would love to see an example/test case.

**Comment by arei** [comment]
also, thank you for contributing.  Super happy for more people to join!

**Comment by moimikey** [comment]
@arei i just really like how clean of an abstraction it is.

re: postcss, if you're familiar with DSLs like Sass and Less (pre-processors), PostCSS is a post-processor, but lets you use modern (CSS 4+) (https://postcss.org)

the `transform` option would let you pass a function which -- in the case of postcss, would be:

```javascript
css(content,options={}) {
...
if (options.transform) {
   css = await options.transform.apply(null, content);
}
...
}
```

> input

```javascript
const postcssCore = require('postcss-js');
const postcss = postcssCore.sync([require('autoprefixer')])
css(`:fullscreen {}`, {
  transform: (content) => postcss().process(content, { from: undefined }).then(result => result.css)
});
```

> output (css)

```css
:-webkit-full-screen {
}
:-moz-full-screen {
}
:-ms-fullscreen {
}
:fullscreen {
}
```

not tested, but i'm wanting to try to do the above.

postcss: https://postcss.org
postcss repl: http://postcss-repl.surge.sh/

**Comment by arei** [comment]
One concern with this approach is it kind of breaks the bundler goal of putting everything into a single file. The postCSS (or whatever) would still be an external file. This approach might still be valid, I may just need to think about ways for the bundler to include other third party apps.

**Comment by arei** [comment]
Tests work better in upcoming 1.2.0 release which should be posted later today. Still interested in your `transform` stuff.

**Comment by arei** [comment]
1.2.0 is now published. Give it a try and let me know if the tests all run for you now and we can close this issue if so.  I would still like an issue opened around your transform stuff though, so perhaps a new one for that?

**Comment by moimikey** [comment]
awesome. tests run. i'll open a separate issue re: the other convo we had with postcss 👍
