### ISSUE TITLE
Pass an object with all definition methods to ZephComponents.define callback

### ISSUE THREAD

**Issue by gbbarroso** [awesomeeng/zephjs#2]
Instead of: 

    import {html,css,attribute,property,bind,onCreate,onEvent} from "./zeph.min.js";

    ZephComponents.define("my-button",()=>{
        html("./my-button.html");
    	css("./my-button.css");
    });

Make this possible:

    ZephComponents.define("my-button",({ html, css }) => {
    	html("./my-button.html");
    	css("./my-button.css");
    });

**Comment by arei** [comment]
Closed for v1.1.0 - https://github.com/awesomeeng/zephjs/commit/df32d5727819a633d86b752d40d1e8b822fa3d5d
