### ISSUE TITLE
Add video() definition method.

### ISSUE THREAD

**Issue by arei** [awesomeeng/zephjs#7]
Add the video() definition method.

This method is important to allow sounds to be bundled by the bundler and making ZephJS "compiled code" standalone as much as possible.

The video definition method takes two arguments:
 - selector: A CSS Query Selector String of the element to apply the audio to;
 - source: The filename (or inline content) of the video to be applied.

Given these two attributes the `video()` method will download the video (if needed) and then use the video on any element that matches the selector and is an `<video>` tag. 

Additionally, the bundler will be updated to inline the `audio()` filename references. This means images thus declared will be inlined into the bundled code.

**Comment by FDiskas** [comment]
Or just use universal method like `asset()`

**Comment by arei** [comment]
I keep going back and forth on this. They do have slightly different needs though. For example `image()` will place the image into the background-image if not an image tag. Cant really do that with video. I could in theory look at the mimetype... hrm. Like I said, I keep going back and forth. I was going to call it `resource()` but I like your `asset()` name better.

**Comment by arei** [comment]
Refactored my current work in progress on this to asset() for all three type (image, audio, video) and find that I like it a lot more.  Thank you for the suggestion.  New version with this in it should be out by the end of the week.

**Comment by arei** [comment]
Fixed in v1.2.0 with the introduction of the `asset()` definition method.
